import DS from 'ember-data';

export default DS.Model.extend({
  type: DS.attr('number'),
  if_index: DS.attr('number'),
  flags: DS.attr('string'),
  address: DS.attr('string'),
  broadcast: DS.attr('string'),
  ifname: DS.attr('string'),
  mtu: DS.attr('number'),
  link: DS.attr('string'),
  qdisc: DS.attr('string'),
  cost: DS.attr('string'),
  priority: DS.attr('string'),
  master: DS.attr('string'),
  wireless: DS.attr('string'),
  protinfo: DS.attr('string'),
  txqlen: DS.attr('number'),
  map: DS.attr('string'),
  weight: DS.attr('string'),
  operstate: DS.attr('string'),
  linkmode: DS.attr('string'),
  linkinfo: DS.attr('string'),
  net_ns_pid: DS.attr('string'),
  ifalias: DS.attr('string'),
  num_vf: DS.attr('string'),
  vfinfo_list: DS.attr('string'),
  vf_ports: DS.attr('string'),
  port_self: DS.attr('string'),
  group: DS.attr('string'),
  net_ns_fd: DS.attr('string'),
  ext_mask: DS.attr('string'),
  promiscuity: DS.attr('string'),
  num_tx_queues: DS.attr('number'),
  num_rx_queues: DS.attr('number'),
  carrier: DS.attr('string'),
  phys_port_id: DS.attr('string'),
  carrier_changes: DS.attr('string'),
  phys_switch_id: DS.attr('string'),
  link_netnsid: DS.attr('string'),
  phys_port_name: DS.attr('string'),
  af_inet_conf: DS.attr('string'),
  af_inet6_flags: DS.attr('string'),
  af_inet6_conf: DS.attr('string'),
  af_inet6_stats: DS.attr('string'),
  af_inet6_cacheinfo: DS.attr('string'),
  af_inet6_icmp6_stats: DS.attr('string'),
  af_inet6_addr_gen_mode: DS.attr('string'),
  addrs: DS.attr(),

  stats: DS.belongsTo('interface-stat'),
});
